### ISSUE TITLE
Additional blog style pages

### ISSUE THREAD

**Issue by jakegalson** [devcows/hugo-universal-theme#103]
I have attempted to make an additional content page similar to the portfolio page in the original bootstrapious theme.

To do this, I copied the _default directory in the layout to make one for "blog" and one for "portfolio". I then edited the "list.html" and "single.html" files in the new portfolio directory to reflect the layout that I wanted. I am happy with the current blog layout, so left that as it is.

When the portfolio page renders, it looks fine (so "portfolio/list.html" works). However, when I click on the link of one of the portfolio items to take me to the single portfolio page, it does not work, and appears to still look under "_default", so "portfolio/single.html" does not seem to be recognised.

Has anyone else successfully achieved something similar to this, or know where I have messed up?

**Comment by GeorgeWL** [comment]
I've had success with this before, think you may have just implemented it imperfectly.

**Comment by jakegalson** [comment]
Yes, it was a stupid mistake on my part.

One of the fields in the header was "type", so it was looking for a layout with the same filename as the type rather than based on the directory name.

**Comment by kmillage** [comment]
I think I'm having the same problem but I can't seem to figure out exactly how you fixed it... I've tried to duplicate the _default directory and change the line in "list.html" which was previously {{ $paginator := .Paginate (where .Data.Pages "Type" "blog") }} to {{ $paginator := .Paginate (where .Data.Pages "Type" "portfolio") }} for the new page (with a matching folder of files called "portfolio" in the content folder). I can get a new "/portfolio/" page to render, but it seems to still be looking to the original "_default" files instead of the duplicates. Am I missing something about how the items within "_default" are getting called? Did you have to change the names of the original and duplicate "_default" folders? Or could you elaborate on your fix? Thanks!

**Comment by jakegalson** [comment]
I have just been looking into what I did, and can't quite remember the details as it was a while ago now. Regarding the line you mention, mine looks like this: {{ $paginator := (.Paginate .Data.Pages) }}

I will continue to investigate. This seems to me like quite a common request, so i think it should either be added to the theme, or some instructions made for how to add the page.

**Comment by kmillage** [comment]
Hmmm that still doesn't do it for me. It looks like everything is in the correct place once it's rendered into the public folder but I can't see it! 

Agreed I think instructions on how to do this would be very beneficial to the theme! Thanks for looking into it and let me know if you remember anything else!
