### ISSUE TITLE
Unable to find archetypes directory for theme "hugo-universal-theme"

### ISSUE THREAD

**Issue by brylie** [devcows/hugo-universal-theme#16]
When trying to run `hugo new page.md`, I get the following error:

> Unable to find archetypes directory for theme "hugo-universal-theme"

Where should archetypes be located for the hugo-universal-theme?

**Comment by adrianmo** [comment]
@brylie thanks for reporting the issue. The error message occurs because the theme didn't have a `archetypes` directory. Please update the theme to the latest version and the error should be gone.

If you still have problems please open a [new issue](https://github.com/devcows/hugo-universal-theme/issues/new).

**Comment by brylie** [comment]
I cloned the theme for the first time this morning. Did the theme get updated to include an 'archtypes' directory today?

**Comment by adrianmo** [comment]
@brylie Did it work?

**Comment by brylie** [comment]
Yep, it worked. It might be helpful to have a couple of different archtypes, for demonstration.
