### ISSUE TITLE
Headlines shown in excerpts

### ISSUE THREAD

**Issue by kttmnn** [devcows/hugo-universal-theme#30]
Hi,

the h2's are shown in the excerpt's p-tag without a full stop on the blog page. 

Eg.:
**Singleview code:**
`## Step 1. Install Hugo`
`Goto [hugo releases](https://github.com/spf13/hugo/releases) and download…`

**Excerpt output:**
`<p class="intro">Step 1. Install Hugo Goto hugo releases and download the…`

**Comment by adrianmo** [comment]
Hi @kttmnn,

I'm afraid we can't do anything from our side since it's an Hugo feature called "Summary".

You can read more about it here: https://gohugo.io/content/summaries/

You may want to use the `<!--more-->` divider in your content to manually define what your summary should contain and preserve HTML tags. 

Hope this helps and sorry for the late reply.
