### ISSUE TITLE
Adding content under folder other than blog

### ISSUE THREAD

**Issue by bhowiebkr** [devcows/hugo-universal-theme#46]
How do I add new content in it’s own group instead of the blog folder?  When creating the folder called “foo” and adding a bar.md file in there, the bar page doesn’t show up, but if I type in the url I can get to that page. 

Is everything hardcoded to only show content in the blog folder? How do I make it work with other folders under content as well.

Do I need to add or change anything into the list.html

**Comment by bhowiebkr** [comment]
I’ve managed to fix it, maybe it’s something to change in the repo as well?

Under:
layouts/_default/list.html
`{{ $paginator := .Paginate (where .Data.Pages "Type" "post") }}`

Was changed to:
`{{ $paginator := (.Paginate .Data.Pages) }}`
This will now show any content type

Create folder:
**layouts/section**

Now copy **layouts/_default/list.html** into **layouts/section** and rename it with the type you want to use and make any changes there.

This is my first day using hugo, so if this is incorrect please let me know. 😄

**Comment by adrianmo** [comment]
Hi @bhowiebkr, it's great that you found out a solution for it :)

I will review it and dig into it later this week and get back to you to let you know the actions taken.

Thanks!

**Comment by bhowiebkr** [comment]
Another issue I found when using the template was when I want to show related of a different type. When trying to display related_posts.html and related_something_else.html I would get the following error:

**theme/partials/recent_posts.html is an incomplete or empty template**

To fix the problem, I replaced the line:


```
{{ $posts := .Paginate (where .Data.Pages "Type" "blog") }}
{{ range first 4 $posts.Pages }}
```
With:

`{{range first 4 (where .Data.Pages "Type" "blog") }}
`

It wasn’t necessary to change it in both template files to fix it, but I did anyways. I’m not sure what the exact issue was with running the code you originally used. I feel like Go html/templating is just not that great with very generic errors when something go wrong.

**Comment by kenan-rhoton** [comment]
Is this being looked at? I can make a Pull Request with the changes if it makes things easier.

**Comment by GeorgeWL** [comment]
@kenan-rhoton would be lovely of you to pull request it please.

**Comment by kenan-rhoton** [comment]
I actually thought I'd done it, sorry. Will do over the weekend.

**Comment by r0berts** [comment]
This issue is still in original source. I tried to understand what was going on for the best of [yesterday](https://discourse.gohugo.io/t/new-section-tags-and-category-not-rendering-what-could-it-be-hugo-universal-theme/13831) before I got to here. The theme is great, this really could be ironed out - in 2 ways. Either there is a design decision why there is restriction to "blog"
    `{{ $paginator := .Paginate (where .Data.Pages "Type" "blog") }}`

in which case it would be good to mention it in theme documentation

or perhaps change the line above to how Bryan did it `{{ $paginator := (.Paginate .Data.Pages) }}`
For the second case for `recent posts` I left it filtering for `blog` because my other sections are more on the static side and I want only recent posts from blog to feature.
