### ISSUE TITLE
Google Maps Error

### ISSUE THREAD

**Issue by Iskenof** [devcows/hugo-universal-theme#68]
Google Maps Error!

![image](https://cloud.githubusercontent.com/assets/9514675/24443412/d2eb2300-1462-11e7-833e-d3eb21dcf26b.png)

![image](https://cloud.githubusercontent.com/assets/9514675/24443438/ecc113de-1462-11e7-9244-fbf5db526bb4.png)

**Comment by schuster-rainer** [comment]
@Iskenof can you post the config you used? Are you using the current master branch?

**Comment by virtualjj** [comment]
I have this same issue:

![image](https://cloud.githubusercontent.com/assets/10323889/25017273/1d4e68d2-20be-11e7-907e-5789dc267315.png)

Here is my config.toml configuration:

![image](https://cloud.githubusercontent.com/assets/10323889/25017215/df39da4a-20bd-11e7-8851-dc0b0d0a8760.png)

Here is my API Key settings:

![image](https://cloud.githubusercontent.com/assets/10323889/25018180/6c9d28e4-20c1-11e7-91e4-10a0907660a8.png)

When I changed the API Key security to unrestricted it works:

![image](https://cloud.githubusercontent.com/assets/10323889/25017395/9934ace0-20be-11e7-9d04-2e9407ba983d.png)

![image](https://cloud.githubusercontent.com/assets/10323889/25017841/22554916-20c0-11e7-9c1e-b0a8b571e574.png)

I'm assuming the issue is related to API Key settings however I'm not seeing or understanding what should be in the referrers list. I tried adding */mydomain.io/* as well but another error message pops up:

![image](https://cloud.githubusercontent.com/assets/10323889/25018380/205f600e-20c2-11e7-9621-3d7674a87853.png)

Perhaps HTTPS is not supported?

**Comment by virtualjj** [comment]
Apologies - didn't think that through. AWS CloudFront uses many edge locations so I'd need to add all those IPs to the address list. Still think the HTTP referrer method should work though.

**Comment by adrianmo** [comment]
@virtualjj thanks for looking into it and finding a solution! 

Cheers,
-Adrian
